controller_list:
  - name: fake_arm_controller
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
  - name: fake_gazebo_tool_controller
    joints:
      - joint_base_to_mors_1
      - joint_base_to_mors_2
